@startuml components
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

AddElementTag("microService", $shape=EightSidedShape(), $bgColor="CornflowerBlue", $fontColor="white", $legendText="microservice")
AddElementTag("storage", $shape=RoundedBoxShape(), $bgColor="lightSkyBlue", $fontColor="white")

Person(moderator, "Модератор")
Person(user, "Пользователь")

System_Ext(web_site, "Клиентский веб-сайт", "HTML, CSS, JavaScript, React", "Веб-интерфейс")

System_Boundary(conference_site, "Сайт социальной сети") {
   Container(client_service, "Сервис авторизации и регистрации", "C++", "Сервис управления пользователями", $tags = "microService")    
   Container(post_service, "Сервис постов", "C++", "Сервис управления новостными лентами пользователей", $tags = "microService") 
   Container(blog_service, "Сервис сообщений", "C++", "Сервис управления доставками и принятиями сообщений пользователями", $tags = "microService")   
   ContainerDb(db, "База данных", "MySQL", "Хранение данных о пользователях, их постах и сообщениях", $tags = "storage")
}

Rel(moderator, web_site, "Модерация контента и пользователей")
Rel(user, web_site, "Регистрация, отправка и принятие сообщений, создание поста на пользовательскую ленту, чтение всей ленты")

Rel(web_site, client_service, "Работа с пользователями", "localhost/person")
Rel(client_service, db, "INSERT/SELECT/UPDATE", "SQL")

Rel(web_site, post_service, "Работа с новстной лентой", "localhost/feed")
Rel(post_service, db, "INSERT/SELECT/UPDATE", "SQL")

Rel(web_site, blog_service, "Работа с сообщениями", "localhost/chat")
Rel(blog_service, db, "INSERT/SELECT/UPDATE", "SQL")

@enduml